import { useMemo, useState } from 'react';
import { useDomainStore } from '../../domain/store';
import { StatusBadge } from '../../components/StatusBadge';
import type { Actor, DomainAction, DomainState } from '../../domain/types';

type FlowKind = 'lead' | 'compliance' | 'quotation' | 'order';
const owner: Actor = { userId: 'user-enterprise-owner', organizationId: 'org-enterprise-wenzhou', projectIds: ['project-wenzhou'], role: 'enterprise_owner' };
const provider: Actor = { userId: 'user-provider', organizationId: 'org-service-provider', projectIds: ['project-wenzhou'], role: 'service_provider' };
const operator: Actor = { userId: 'user-product-operator', organizationId: 'org-enterprise-wenzhou', projectIds: ['project-wenzhou'], role: 'product_operator' };

export function FlowPage({ kind }: { kind: FlowKind; navigate: (route: string) => void }) {
  const { state, dispatch } = useDomainStore(); const [error, setError] = useState('');
  const current = useMemo(() => currentStatus(kind, state), [kind, state]); const action = nextAction(kind, state);
  const run = (actionToRun: DomainAction) => { try { setError(''); dispatch(actionToRun); } catch (cause) { setError(cause instanceof Error ? cause.message : '操作未完成'); } };
  const doNext = () => { if (action) run(action); };
  return <div className="page-stack">{error && <div className="inline-error" role="alert">{error}</div>}<section className="flow-simple"><div className="flow-simple-bar"><h2>{objectName(kind, state)}</h2><StatusBadge status={current} /></div><div className="flow-simple-body"><div className="flow-simple-facts">{factsFor(kind, state).map(([label, value]) => <p key={label}><b>{label}</b><span>{value}</span></p>)}</div><div className="flow-simple-action"><button type="button" disabled={!action} onClick={doNext}>{actionLabel(kind, state)} →</button><p className="admin-footnote">{kind === 'lead' ? '推进后同步客户画像、触达任务和商机。' : kind === 'compliance' ? '风险、材料和复核全部完成后案件通过。' : kind === 'quotation' ? '客户反馈与报价版本分开记录，旧版本只读。' : '节点、风险、入库和库存共同决定订单完成。'}</p></div></div></section></div>;
}

function currentStatus(kind: FlowKind, state: DomainState) { return kind === 'lead' ? state.leads[0].status : kind === 'compliance' ? state.complianceCases[0].status : kind === 'quotation' ? state.quotations[0].status : state.orders[0].status; }
function objectName(kind: FlowKind, state: DomainState) { return kind === 'lead' ? state.leads[0].name : kind === 'compliance' ? `境外商品合规 · ${state.complianceCases[0].scope}` : kind === 'quotation' ? `报价单 · 版本 ${state.quotations[0].currentVersion}` : `订单 · ${state.orders[0].id}`; }
function nextAction(kind: FlowKind, state: DomainState): DomainAction | undefined { if (kind === 'lead') { const lead = state.leads[0]; const events: Record<string, 'confirm' | 'processing_complete' | 'store' | 'assign' | 'touch' | 'follow_up' | 'convert'> = { 待筛选: 'confirm', 处理中: 'processing_complete', 待确认: 'store', 已入库: 'assign', 已分配: 'touch', 已触达: 'follow_up', 跟进中: 'convert' }; const event = events[lead.status]; return event ? { type: 'leadEvent', actor: operator, leadId: lead.id, event, idempotencyKey: `flow-lead-${event}-${lead.status}` } : undefined; } if (kind === 'compliance') { const risk = state.risks[0]; const task = state.rectificationTasks[0]; const material = state.complianceMaterials[0]; const item = state.complianceCases[0]; if (risk.status === '已确认') return { type: 'riskItemEvent', actor: owner, riskId: risk.id, event: 'start_rectification' }; if (task.status === '待处理') return { type: 'rectificationTaskEvent', actor: provider, taskId: task.id, event: 'start' }; if (task.status === '处理中') return { type: 'rectificationTaskEvent', actor: provider, taskId: task.id, event: 'submit' }; if (material.status === '已提交') return { type: 'complianceMaterialEvent', actor: owner, materialId: material.id, event: 'confirm' }; if (item.status === '待整改') return { type: 'complianceCaseEvent', actor: owner, caseId: item.id, event: 'submit_review' }; if (risk.status === '待复核') return { type: 'riskResolve', actor: owner, riskId: risk.id }; if (item.status === '已通过') return { type: 'complianceCaseEvent', actor: owner, caseId: item.id, event: 'archive' }; return undefined; } if (kind === 'quotation') { const quotation = state.quotations[0]; if (quotation.status === '已发送') return { type: 'quotationFeedback', actor: owner, quotationId: quotation.id, feedback: 'viewed', idempotencyKey: 'flow-quote-viewed' }; if (quotation.status === '客户已查看') return { type: 'quotationFeedback', actor: owner, quotationId: quotation.id, feedback: 'negotiating', idempotencyKey: 'flow-quote-negotiating' }; if (quotation.status === '议价中') return { type: 'quotationFeedback', actor: owner, quotationId: quotation.id, feedback: 'accepted', idempotencyKey: 'flow-quote-accepted' }; return undefined; } const node = state.fulfillmentNodes[0]; const order = state.orders[0]; if (node.status === '未开始') return { type: 'fulfillmentNodeEvent', actor: operator, nodeId: node.id, orderId: order.id, event: 'start' }; if (node.status === '处理中') return { type: 'fulfillmentNodeEvent', actor: operator, nodeId: node.id, orderId: order.id, event: 'risk', riskEventId: `risk-event-${node.id}` }; if (node.status === '存在风险') return { type: 'fulfillmentNodeEvent', actor: operator, nodeId: node.id, orderId: order.id, event: 'resolve', riskEventId: `risk-event-${node.id}` }; return undefined; }
function actionLabel(kind: FlowKind, state: DomainState) { if (kind === 'lead') return '推进线索状态'; if (kind === 'compliance') return state.risks[0].status === '待复核' ? '确认风险已解除' : '推进合规处理'; if (kind === 'quotation') return state.quotations[0].status === '议价中' ? '记录客户接受' : state.quotations[0].status === '已接受' ? '创建新报价版本' : '记录客户反馈'; return state.fulfillmentNodes[0].status === '处理中' ? '标记履约风险' : state.fulfillmentNodes[0].status === '存在风险' ? '解除履约风险' : '完成履约节点'; }
function factsFor(kind: FlowKind, state: DomainState): [string, string][] { if (kind === 'lead') return [['客户画像', state.customerProfiles[0].status], ['触达任务', state.touchTasks[0].status], ['跟进记录', state.followUps[0].status]]; if (kind === 'compliance') return [['风险项', state.risks[0].status], ['整改任务', state.rectificationTasks[0].status], ['材料', state.complianceMaterials[0].status], ['复核', state.reviewRecords[0].status]]; if (kind === 'quotation') return [['报价金额', `¥ ${state.quotations[0].amount.toLocaleString()}`], ['当前版本', String(state.quotations[0].currentVersion)], ['客户反馈', state.quotations[0].status]]; return [['履约节点', state.fulfillmentNodes[0].status], ['风险事件', state.riskEvents[0]?.status ?? '未创建'], ['入库记录', state.inboundRecords[0].status], ['库存数量', String(state.inventories[0].quantity)]]; }
