import { useMemo, useState } from 'react';
import { useDomainStore } from '../../domain/store';
import { StatusBadge } from '../../components/StatusBadge';
import { Timeline } from '../../components/Timeline';
import { selectTimeline } from '../../domain/selectors';
import type { Actor, DomainAction, DomainState } from '../../domain/types';

type FlowKind = 'lead' | 'compliance' | 'quotation' | 'order';
const owner: Actor = { userId: 'user-enterprise-owner', organizationId: 'org-enterprise-wenzhou', projectIds: ['project-wenzhou'], role: 'enterprise_owner' };
const provider: Actor = { userId: 'user-provider', organizationId: 'org-service-provider', projectIds: ['project-wenzhou'], role: 'service_provider' };
const operator: Actor = { userId: 'user-product-operator', organizationId: 'org-enterprise-wenzhou', projectIds: ['project-wenzhou'], role: 'product_operator' };

export function FlowPage({ kind, navigate }: { kind: FlowKind; navigate: (route: string) => void }) {
  const { state, dispatch } = useDomainStore(); const [error, setError] = useState('');
  const config = { lead: ['线索经营', '把全球采购商线索变成可跟进的客户关系。', 'Lead', 'lead-demo'], compliance: ['合规处理', '材料、风险、整改和复核共同决定案件是否通过。', 'ComplianceCase', 'case-demo'], quotation: ['询价与报价', '把客户需求转成可比较、可确认、可追踪的报价版本。', 'Quotation', 'quotation-demo'], order: ['订单与履约', '围绕订单节点推进备货、风险、入库和交付。', 'Order', 'order-demo'] }[kind];
  const current = useMemo(() => currentStatus(kind, state), [kind, state]); const action = nextAction(kind, state);
  const run = (actionToRun: DomainAction) => { try { setError(''); dispatch(actionToRun); } catch (cause) { setError(cause instanceof Error ? cause.message : '操作未完成'); } };
  const doNext = () => { if (action) run(action); };
  return <div className="page-stack"><button className="back-link" type="button" onClick={() => navigate('/')}>← 返回场景中心</button><div className="page-intro"><div><span className="eyebrow">五条主线 / {config[0]}</span><h1>{config[0]}</h1><p>{config[1]}</p></div><StatusBadge status={current} /></div>{error && <div className="inline-error" role="alert">{error}</div>}<section className="flow-board"><div className="flow-rail">{stepsFor(kind).map((step, index) => <div className={index === stepIndex(kind, state) ? 'flow-step is-current' : 'flow-step'} key={step}><span>0{index + 1}</span><strong>{step}</strong></div>)}</div><div className="flow-main"><div className="flow-heading"><div><span className="eyebrow">当前业务对象 / {config[2]}</span><h2>{objectName(kind, state)}</h2></div><StatusBadge status={current} /></div><div className="flow-detail-grid"><div className="result-card"><div className="result-icon">{iconFor(kind)}</div><div><span className="eyebrow">下一步</span><h3>{nextLabel(kind, state)}</h3><p>{nextHelp(kind, state)}</p>{action && <button type="button" onClick={doNext}>{actionLabel(kind, state)} →</button>}</div></div><div className="flow-object-facts">{factsFor(kind, state).map(([label, value]) => <p key={label}><b>{label}</b><span>{value}</span></p>)}</div></div><div className="flow-foot"><span>正式对象状态：{current}</span><span>处理记录已保留</span><span>下一步任务自动生成</span></div></div></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">处理记录</span><h2>这条业务主线留下什么</h2></div><button className="text-button" type="button" onClick={() => navigate('/data')}>去业务数据 →</button></div><Timeline entries={timelineFor(kind, state)} /></section></div>;
}

function stepsFor(kind: FlowKind) { return kind === 'lead' ? ['筛选线索', '确认入库', '分配负责人', '触达跟进'] : kind === 'compliance' ? ['提交材料', '识别风险', '整改复核', '通过归档'] : kind === 'quotation' ? ['确认需求', '组合方案', '发送报价', '承接反馈'] : ['确认订单', '推进节点', '处理风险', '完成履约']; }
function iconFor(kind: FlowKind) { return kind === 'lead' ? '◎' : kind === 'compliance' ? '!' : kind === 'quotation' ? '¥' : '↗'; }
function currentStatus(kind: FlowKind, state: DomainState) { return kind === 'lead' ? state.leads[0].status : kind === 'compliance' ? state.complianceCases[0].status : kind === 'quotation' ? state.quotations[0].status : state.orders[0].status; }
function objectName(kind: FlowKind, state: DomainState) { return kind === 'lead' ? state.leads[0].name : kind === 'compliance' ? `境外商品合规 · ${state.complianceCases[0].scope}` : kind === 'quotation' ? `报价单 · 版本 ${state.quotations[0].currentVersion}` : `订单 · ${state.orders[0].id}`; }
function stepIndex(kind: FlowKind, state: DomainState) { const status = currentStatus(kind, state); if (kind === 'lead') return ['待筛选', '处理中', '待确认', '已入库', '已分配', '已触达', '跟进中'].indexOf(status) >= 3 ? 2 : status === '待确认' ? 1 : 0; if (kind === 'compliance') return ['待受理', '处理中', '待补充材料', '待整改', '待复核', '已通过', '已归档'].indexOf(status) >= 4 ? 2 : status === '待整改' ? 1 : 0; if (kind === 'quotation') return ['草稿', '待确认', '已发送', '客户已查看', '议价中', '已接受'].indexOf(status) >= 3 ? 3 : 0; return ['草稿', '待确认', '已确认', '执行中', '部分完成', '已完成'].indexOf(status) >= 2 ? 1 : 0; }
function nextAction(kind: FlowKind, state: DomainState): DomainAction | undefined { if (kind === 'lead') { const lead = state.leads[0]; const events: Record<string, 'confirm' | 'processing_complete' | 'store' | 'assign' | 'touch' | 'follow_up' | 'convert'> = { 待筛选: 'confirm', 处理中: 'processing_complete', 待确认: 'store', 已入库: 'assign', 已分配: 'touch', 已触达: 'follow_up', 跟进中: 'convert' }; const event = events[lead.status]; return event ? { type: 'leadEvent', actor: operator, leadId: lead.id, event, idempotencyKey: `flow-lead-${event}-${lead.status}` } : undefined; } if (kind === 'compliance') { const risk = state.risks[0]; const task = state.rectificationTasks[0]; const material = state.complianceMaterials[0]; const item = state.complianceCases[0]; if (risk.status === '已确认') return { type: 'riskItemEvent', actor: owner, riskId: risk.id, event: 'start_rectification' }; if (task.status === '待处理') return { type: 'rectificationTaskEvent', actor: provider, taskId: task.id, event: 'start' }; if (task.status === '处理中') return { type: 'rectificationTaskEvent', actor: provider, taskId: task.id, event: 'submit' }; if (material.status === '已提交') return { type: 'complianceMaterialEvent', actor: owner, materialId: material.id, event: 'confirm' }; if (item.status === '待整改') return { type: 'complianceCaseEvent', actor: owner, caseId: item.id, event: 'submit_review' }; if (risk.status === '待复核') return { type: 'riskResolve', actor: owner, riskId: risk.id }; if (item.status === '已通过') return { type: 'complianceCaseEvent', actor: owner, caseId: item.id, event: 'archive' }; return undefined; } if (kind === 'quotation') { const quotation = state.quotations[0]; if (quotation.status === '已发送') return { type: 'quotationFeedback', actor: owner, quotationId: quotation.id, feedback: 'viewed', idempotencyKey: 'flow-quote-viewed' }; if (quotation.status === '客户已查看') return { type: 'quotationFeedback', actor: owner, quotationId: quotation.id, feedback: 'negotiating', idempotencyKey: 'flow-quote-negotiating' }; if (quotation.status === '议价中') return { type: 'quotationFeedback', actor: owner, quotationId: quotation.id, feedback: 'accepted', idempotencyKey: 'flow-quote-accepted' }; return { type: 'reviseQuotation', actor: owner, quotationId: quotation.id, amount: quotation.amount + 500, combination: [...quotation.combination, '增值服务'], idempotencyKey: `flow-quote-revise-${quotation.currentVersion}` }; } const node = state.fulfillmentNodes[0]; if (node.status === '处理中') return { type: 'fulfillmentNodeEvent', actor: owner, nodeId: node.id, orderId: 'order-demo', event: 'risk', riskEventId: 'risk-event-demo' }; if (node.status === '存在风险') return { type: 'fulfillmentNodeEvent', actor: owner, nodeId: node.id, orderId: 'order-demo', event: 'resolve', riskEventId: 'risk-event-demo' }; return { type: 'fulfillmentNodeEvent', actor: owner, nodeId: node.id, orderId: 'order-demo', event: 'complete', inboundRecordId: 'inbound-demo', inventoryId: 'inventory-demo', riskEventId: 'risk-event-demo' }; }
function actionLabel(kind: FlowKind, state: DomainState) { if (kind === 'lead') return '推进线索状态'; if (kind === 'compliance') return state.risks[0].status === '待复核' ? '确认风险已解除' : '推进合规处理'; if (kind === 'quotation') return state.quotations[0].status === '议价中' ? '记录客户接受' : state.quotations[0].status === '已接受' ? '创建新报价版本' : '记录客户反馈'; return state.fulfillmentNodes[0].status === '处理中' ? '标记履约风险' : state.fulfillmentNodes[0].status === '存在风险' ? '解除履约风险' : '完成履约节点'; }
function nextLabel(kind: FlowKind, state: DomainState) { return actionLabel(kind, state); }
function nextHelp(kind: FlowKind, state: DomainState) { if (kind === 'lead') return `当前状态为 ${state.leads[0].status}，推进后会同步客户画像、触达任务和商机。`; if (kind === 'compliance') return '每个风险、材料和复核记录都要完成，案件才会进入通过状态。'; if (kind === 'quotation') return '客户反馈与报价版本是两类记录，旧版本保留只读。'; return '节点、风险事件、入库和库存变化共同决定订单是否完成。'; }
function factsFor(kind: FlowKind, state: DomainState): [string, string][] { if (kind === 'lead') return [['客户画像', state.customerProfiles[0].status], ['触达任务', state.touchTasks[0].status], ['跟进记录', state.followUps[0].status]]; if (kind === 'compliance') return [['风险项', state.risks[0].status], ['整改任务', state.rectificationTasks[0].status], ['材料', state.complianceMaterials[0].status], ['复核', state.reviewRecords[0].status]]; if (kind === 'quotation') return [['报价金额', `¥ ${state.quotations[0].amount.toLocaleString()}`], ['当前版本', String(state.quotations[0].currentVersion)], ['客户反馈', state.quotations[0].status]]; return [['履约节点', state.fulfillmentNodes[0].status], ['风险事件', state.riskEvents[0]?.status ?? '未创建'], ['入库记录', state.inboundRecords[0].status], ['库存数量', String(state.inventories[0].quantity)]]; }
function timelineFor(kind: FlowKind, state: DomainState) { const type = kind === 'lead' ? 'Lead' : kind === 'compliance' ? 'ComplianceCase' : kind === 'quotation' ? 'Quotation' : 'Order'; const id = kind === 'lead' ? 'lead-demo' : kind === 'compliance' ? 'case-demo' : kind === 'quotation' ? 'quotation-demo' : 'order-demo'; return selectTimeline(state, type, id, kind === 'compliance' ? owner : kind === 'lead' ? operator : owner); }
