import { useState } from 'react';
import type { DomainState } from '../../domain/types';
import { useDomainStore } from '../../domain/store';
import { StatusBadge } from '../../components/StatusBadge';

export function ProductWorkspace({ id = 'product-demo', navigate }: { id?: string; navigate: (route: string) => void }) {
  const { state, dispatch } = useDomainStore(); const [tab, setTab] = useState('商品信息'); const [error, setError] = useState('');
  const actor = { userId: 'user-enterprise-owner', organizationId: 'org-enterprise-wenzhou', projectIds: ['project-wenzhou'], role: 'enterprise_owner' as const };
  const product = state.products.find((item) => item.id === id) ?? state.products[0]; const candidate = state.candidates.find((item) => item.targetObject.type === 'Product' && item.targetObject.id === product.id && ['待确认', '写回失败'].includes(item.status)); const compliance = state.complianceCases.find((item) => item.subjectType === 'Product' && item.subjectId === product.id); const risks = state.risks.filter((item) => item.caseId === compliance?.id);
  const run = (action: Parameters<typeof dispatch>[0]) => { try { setError(''); dispatch(action); } catch (cause) { setError(cause instanceof Error ? cause.message : '操作未完成'); } };
  const confirm = () => { if (!candidate) return; run({ type: 'confirmCandidate', actor, candidateId: candidate.id, idempotencyKey: `product-confirm-${candidate.id}-${candidate.candidateVersion}` }); };
  return <div className="page-stack"><div className="product-header"><h1>{product.name}</h1><div><StatusBadge status={product.status} /><span className="version-label">版本 {product.currentVersion}</span></div></div><div className="product-tabs">{['商品信息', '图片与视频', '多语言内容', '合规检查', '发布记录'].map((item) => <button className={tab === item ? 'tab is-active' : 'tab'} key={item} type="button" onClick={() => setTab(item)}>{item}</button>)}</div>{error && <div className="inline-error" role="alert">{error}</div>}<section className="product-layout"><div className="panel product-main">{tab === '商品信息' && <><h2>商品基础信息</h2><div className="product-fields"><p><b>商品名称</b>{product.name}</p><p><b>商品描述</b>{product.description}</p><p><b>负责人</b>{product.ownerId}</p><p><b>商品状态</b><StatusBadge status={product.status} /></p></div></>}{tab === '图片与视频' && <><h2>商品图片与场景素材</h2><div className="asset-placeholder"><span>▧</span><strong>rack-demo.jpg</strong><small>商品主图 · 已进入素材库 · 待确认</small></div></>}{tab === '多语言内容' && <><h2>内容版本确认</h2>{candidate ? <div className="candidate-compare"><div><span>当前正式描述</span><p>{product.description}</p></div><div><span>候选描述 · 来源版本 {candidate.sourceVersion}</span><p>{String(candidate.payload.description ?? '')}</p></div></div> : <div className="empty-state"><strong>当前没有待确认候选结果</strong></div>}</>}{tab === '合规检查' && <><h2>合规处理</h2><div className="risk-list">{risks.map((risk) => <div className="risk-row" key={risk.id}><span>!</span><div><strong>{risk.title}</strong><small>风险项 · {risk.status}</small></div><StatusBadge status={risk.status} /></div>)}</div><button className="button-quiet" type="button" onClick={() => navigate('/compliance')}>进入合规处理 →</button></>}{tab === '发布记录' && <><h2>发布准备</h2><div className="publish-gate"><StatusBadge status={product.status} /><strong>{product.status === '可经营' ? '商品可以进入发布任务' : '完成合规处理后才能发布'}</strong></div></>}</div><aside className="product-side"><div className="side-card"><span className="eyebrow">当前建议</span><h3>{candidate ? '确认候选商品内容' : product.status === '需整改' ? '先完成合规整改' : '继续维护商品经营'}</h3>{candidate && <button type="button" onClick={confirm}>确认并写入正式版本 →</button>}{product.status === '需整改' && <button className="button-quiet" type="button" onClick={() => navigate('/compliance')}>处理合规风险 →</button>}</div></aside></section></div>;
}
