import { selectRoleVisibleRecords } from '../domain/selectors';
import type { DomainState } from '../domain/types';
import { ObjectSummary } from '../components/ObjectSummary';
import { StatusBadge } from '../components/StatusBadge';
import { TaskList } from '../components/TaskList';

export function PlaceholderPage({ kind, state, navigate }: { kind: 'tasks' | 'data' | 'analytics' | 'product' | 'leads' | 'compliance' | 'quotation' | 'order' | 'mini'; state: DomainState; navigate: (route: string) => void }) {
  const actor = { userId: 'user-enterprise-owner', organizationId: 'org-enterprise-wenzhou', projectIds: ['project-wenzhou'], role: 'enterprise_owner' as const };
  const records = selectRoleVisibleRecords(state, actor);
  const config = {
    tasks: ['我的工作', '把确认、跟进和风险处理集中在一个工作队列里。'], data: ['业务数据', '业务结果不止是一份输出，它们会沉淀为可持续经营的对象。'], analytics: ['经营分析', '从商品、客户、订单和风险对象汇总经营结果。'], product: ['商品经营', '从一张图片开始，完善商品，确认正式版本，再进入发布。'], leads: ['线索经营', '发现采购商，确认线索，分配负责人并进入持续跟进。'], compliance: ['合规处理', '材料、风险、整改和复核共同决定业务是否可以继续。'], quotation: ['询价与报价', '把客户需求转成可比较、可确认、可追踪的报价版本。'], order: ['订单与履约', '围绕订单节点推进备货、风险、入库和交付。'], mini: ['小程序工作台', '移动端负责快速发起、确认、提醒和跟进，复杂处理回到 Web。'],
  }[kind];
  if (kind === 'tasks') return <div className="page-stack"><PageIntro eyebrow="我的工作" title={config[0]} detail={config[1]} /><section className="panel"><TaskList tasks={records.tasks} /></section></div>;
  if (kind === 'mini') return <div className="page-stack"><PageIntro eyebrow="移动端预览" title={config[0]} detail={config[1]} /><div className="mobile-preview"><div className="phone-screen"><div className="phone-notch" /><div className="phone-head"><span>9:41</span><b>商品工作台</b><span>•••</span></div><div className="phone-greeting"><small>林负责人，今天</small><h2>有 3 件工作<br />等你确认</h2></div><div className="phone-card"><span>商品经营</span><strong>仓储货架</strong><p>商品描述已准备好，等待确认正式版本</p><button type="button" onClick={() => navigate('/product')}>去 Web 完成处理 →</button></div><div className="phone-card phone-card-light"><span>快捷发起</span><div className="phone-actions"><b>拍摄商品</b><b>上传素材</b><b>查看线索</b></div></div><div className="phone-tab"><span>首页</span><span>工作</span><span>数据</span><span>我的</span></div></div></div></div>;
  if (kind === 'data') return <div className="page-stack"><PageIntro eyebrow="业务数据" title={config[0]} detail={config[1]} /><div className="data-grid">{records.products.map((item) => <ObjectSummary key={item.id} label="商品" name={item.name} status={item.status} meta="商品主档 · 素材 · 正式版本" onOpen={() => navigate('/product')} />)}{records.leads.map((item) => <ObjectSummary key={item.id} label="采购商线索" name={item.name} status={item.status} meta="客户画像 · 触达 · 跟进" onOpen={() => navigate('/leads')} />)}{records.complianceCases.map((item) => <ObjectSummary key={item.id} label="合规案件" name={`${item.scope}商品合规`} status={item.status} meta="材料 · 风险 · 复核" onOpen={() => navigate('/compliance')} />)}{records.quotations.map((item) => <ObjectSummary key={item.id} label="报价单" name={`报价 ${item.amount.toLocaleString()}`} status={item.status} meta={`版本 ${item.currentVersion} · 客户反馈`} onOpen={() => navigate('/quotation')} />)}{records.orders.map((item) => <ObjectSummary key={item.id} label="订单" name={item.id} status={item.status} meta="履约 · 节点 · 库存" onOpen={() => navigate('/order')} />)}</div></div>;
  if (kind === 'analytics') return <div className="page-stack"><PageIntro eyebrow="经营分析" title={config[0]} detail={config[1]} /><div className="analytics-hero"><div><span className="eyebrow">本月经营脉搏</span><strong>业务对象正在持续沉淀</strong><p>从处理记录到正式数据，每一步都留下可追溯的经营信号。</p></div><div className="signal-bars"><i style={{height:'38%'}} /><i style={{height:'55%'}} /><i style={{height:'48%'}} /><i style={{height:'72%'}} /><i style={{height:'64%'}} /><i style={{height:'88%'}} /><i style={{height:'78%'}} /></div></div><div className="metric-strip"><div><span>商品档案</span><strong>{records.products.length}</strong><small>正式经营对象</small></div><div><span>客户线索</span><strong>{records.leads.length}</strong><small>待持续跟进</small></div><div><span>报价版本</span><strong>{state.quotationVersions.length}</strong><small>可追溯版本</small></div><div><span>风险项</span><strong>{state.risks.filter((item) => !['已解除','已关闭','已豁免'].includes(item.status)).length}</strong><small>持续监测中</small></div></div></div>;
  return <div className="page-stack"><PageIntro eyebrow="业务场景" title={config[0]} detail={config[1]} action={kind === 'product' ? '查看小程序预览' : undefined} onAction={kind === 'product' ? () => navigate('/mini-program') : undefined} /><section className="flow-board"><div className="flow-rail">{['选择业务对象','填写或上传材料','查看处理结果','确认并沉淀'].map((step, index) => <div className={index === 0 ? 'flow-step is-current' : 'flow-step'} key={step}><span>0{index + 1}</span><strong>{step}</strong></div>)}</div><div className="flow-main"><div className="flow-heading"><div><span className="eyebrow">当前业务对象</span><h2>{kind === 'product' ? '仓储货架' : kind === 'leads' ? 'Global Warehouse Buyer' : kind === 'compliance' ? '境外商品合规' : kind === 'quotation' ? '报价单 quotation-demo' : '订单 order-demo'}</h2></div><StatusBadge status={kind === 'product' ? state.products[0].status : kind === 'leads' ? state.leads[0].status : kind === 'compliance' ? state.complianceCases[0].status : kind === 'quotation' ? state.quotations[0].status : state.orders[0].status} /></div><div className="result-card"><div className="result-icon">{kind === 'product' ? '▧' : kind === 'leads' ? '◎' : kind === 'compliance' ? '!' : kind === 'quotation' ? '¥' : '↗'}</div><div><span className="eyebrow">下一步建议</span><h3>{kind === 'product' ? '确认商品描述，进入合规检查' : kind === 'leads' ? '确认采购商并分配负责人' : kind === 'compliance' ? '补充材料并完成风险整改' : kind === 'quotation' ? '查看报价版本与客户反馈' : '跟踪备货节点并处理风险'}</h3><p>候选结果与正式业务数据分开保存。确认后，系统会写回对应的业务对象，并生成下一步任务。</p><button type="button" onClick={() => navigate('/tasks')}>查看下一步任务 →</button></div></div><div className="flow-foot"><span>场景处理记录</span><span>业务对象版本</span><span>任务与通知</span><span>审计记录</span></div></div></section></div>;
}

function PageIntro({ eyebrow, title, detail, action, onAction }: { eyebrow: string; title: string; detail: string; action?: string; onAction?: () => void }) {
  return <div className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{detail}</p></div>{action && <button type="button" onClick={onAction}>{action} →</button>}</div>;
}
